---
title: "DS 4420 HW4: Time Series"
author: "EmilyNguyen, LenaTong"
date: "2026-03-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Time Series with Crime Data in Los Angeles

## Load necessaries libraries

```{r, message=FALSE, warning=FALSE}
library(zoo)   # For time series manipulation
library(stats)  # For AR model fitting
library(TSA)    # For time series analysis
library(ggplot2)  # For visualization
library(knitr) # For pretty table
library(dplyr) # For data aggregation
library(lubridate)
```

## Load the dataset

```{r}
crime <- read.csv("CrimeData.csv", stringsAsFactors = T)

# Preview the data, only show first 5 columns
kable(head(crime[, 1:5]))
```

## Sort the data 
```{r}
# Sort by DATE.OCC, TIME.OCCM and Date.Rptd in ascending order (oldest first)
crime <- crime[order(crime$DATE.OCC, crime$TIME.OCC, crime$Date.Rptd), ]

# Preview the data, only show first 5 columns
kable(head(crime[, 1:5]))
```

## Crimes based on Date occuring

```{r}
# Add new column for a cleaner date
crime$Date_Clean <- as.Date(crime$DATE.OCC, format = "%m/%d/%Y")

# Aggregate crimes by date
daily_crimes <- crime %>%
  mutate(Date = as.Date(Date_Clean)) %>%
  group_by(Date) %>%
  summarise(Count = n())

kable(head(daily_crimes))
```

## Visualize Time Series

```{r}
ggplot(daily_crimes, aes(x = Date, y = Count)) +
  geom_line() +
  ggtitle('Number of Crimes in Los Angeles over time') +
  xlab('Date') +
  ylab('Number of Crimes') +
  theme_minimal()
```

## ACF Plot

```{r}
acf(daily_crimes$Count, main = "ACF Plot for Number of Crimes")
```
## PACF Plot for Number of Crimes

```{r}
pacf(daily_crimes$Count, main = "PACF Plot for Number of Crimes")
```

